apiVersion: apps/v1
kind: Deployment
metadata:
  name: worklink-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worklink-frontend
  template:
    metadata:
      labels:
        app: worklink-frontend
    spec:
      containers:
      - name: frontend
        image: singhnikhil212/worklink-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80